### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by CybexDex** [ekuro/binance-api#1]
Hello ekuro,

I'm one of the maintainers of CybexDex. We've noticed that you provided many good issues and we are very happy for your work. Can we get a connect method to you? Maybe we can talk a little deeper about those bugs and more over. I cant find the email on your github profile page, so here I create a issue, I hope you'll see the notice sent by github. I hope this behavior won't makes you feel uncomfortable.  

David, CybexTeam.

**Comment by ekuro** [comment]
Dear Cybex Team,

Thank you for issuing.
My email address is 'eiji0513@gmail.com', so please inquire by e-mail.

**Comment by ekuro** [comment]
@CybexDex
